version: "3.8"

services:
  traefik:
    image: library/traefik:v2.3
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.mysql.address=:3306"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - todolist

  mysql:
    image: mysql:5.7
    networks:
      - todolist
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - todolist
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`pma.docker.localhost`)"
      - "traefik.http.routers.pma.entrypoints=web"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

networks:
  todolist:
    external: true
